### ISSUE TITLE
New CITIfile Version

### ISSUE THREAD

**Issue by j-bau** [TitorX/CITIfile#1]
Hi,
It seems that there is a newer version of CITIfile available "CITIFILE A.01.01". Therefor no output is generated with your strict version check "line.startswith("CITIFILE A.01.00")". If one allows the newer Version everything works as expected.

Additionally I do not know if comments came with this new version, indicated by "!" as first character of the line. In my case it mixed up with the NAME finding algorithm. Thus I changed the code to:
```python
def parse_package(lines):
    ...
    while lines:
        line = lines.pop(0)
        if line[0] == '!':
            continue # comment
        else:
            line = line[:-1].split(" ")

        if line[0] == "VAR":
            length = int(line[-1])  # amount of data points
            dtype = np.float if line[-2] == "MAG" else np.complex  # data type

            shape.append(length)
            array = np.zeros(length, dtype)
            var_list.append((line[1], array))

        elif line[0] == "NAME":
            name = line[-1]
        ...
```

**Comment by andypfau** [comment]
Hi,
regarding your first point, my pull-request to support 1.01 was just merged. Maybe you can give it a try :-)
BR, Andy
